[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "map-app"
version = "0.1.2"
description = "Reusable Django map app framework"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "Django>=5.0,<7.0",
  "django-admin-sortable2>=2.2",
  "Pillow>=10.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
