# Generated by Django 6.0.2 on 2026-07-13 04:14

import map_app.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_app', '0003_activitylog_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitylog',
            name='date',
            field=models.DateField(default=map_app.base_models.default_activity_log_date, verbose_name='記録日'),
        ),
    ]
